Update system tests schema config
cloudify-cosmo/cloudify-system-tests pull request #1142
Opened 2021-02-03 14:27 UTC by mabuaisha

2021-02-03 16:04 UTC, YoniItzhak requested changes

2021-02-03 16:04 UTC, YoniItzhak commented on cosmo_tester/config_schemas/cfy_cluster_manager.yaml
> +5_1_2_manager_install_rpm_path:
This is not needed for now. I'll add it if needed.

2021-02-03 16:04 UTC, YoniItzhak commented on cosmo_tester/config_schemas/cfy_cluster_manager.yaml
> +5_2_0_manager_install_rpm_path:
This is not needed for now. I'll add it if needed.

2021-02-03 16:04 UTC, YoniItzhak commented on cosmo_tester/config_schemas/cfy_manager_upgrade.yaml
> +  default: '5.3.0'
This should stay `5.1.2`, as it tests the command `cfy_manager upgrade` and this command cannot be used with `5.3.0`.

2021-02-04 08:40 UTC, mateumann requested changes
isn't it lacking (some) stuff for 5.2.0 (e.g. 5_2_0_manager_install_rpm_path)?
… also manager_image_names_centos.yaml has invalid image for "5_2_0" (I guess should be cfy-manager-premium-5.2.0)
(same comment for manager_image_names_rhel.yaml)

2021-02-04 08:44 UTC, mabuaisha commented
@mateumann thanks for your review, I fixed the invalid image name for redhat and centos and regarding the cluster upgrade path @YoniItzhak will update that as he mentioned that in his review

2021-02-04 08:46 UTC, mateumann submitted a review, later dismissed
stuff related to `5_2_0_manager_install_rpm_path` will be added later

2021-02-14 08:01 UTC, YoniItzhak commented on cosmo_tester/config_schemas/manager_image_names_centos.yaml
> +  description: Name of manager image for 5.1.2. All non master images are only used for upgrade tests.
Should be changed to " Name of image with 5.1.2 manager installer for bootstrap or cluster installs."

2021-02-14 08:14 UTC, YoniItzhak approved these changes

2021-02-14 08:14 UTC, merged